import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_money_formatter/flutter_money_formatter.dart';
import 'package:http/http.dart' as http;
import 'package:nusa_go/model/home.dart';

class HomeFragment extends StatefulWidget {
  @override
  _HomeFragmentState createState() => _HomeFragmentState();
}

class _HomeFragmentState extends State<HomeFragment> {
  List<Home> list = List();
  var isLoading = false;
  var height = 150.0;


  _fetchData() async {
    setState(() {
      isLoading = true;
    });
    final response =
    await http.get("https://nusa-go.com/api/tampilPaketLiburanHome.php?base=flutter");
    if (response.statusCode == 200) {
      print(response.body);
      list = (json.decode(response.body) as List)
          .map((data) => new Home.fromJson(data))
          .toList();
//      final jsonData = json.decode(response.body);
//      Autogenerated a = Autogenerated.fromJson(jsonData);
      setState(() {
//        _jsonContent = a.toString();
        // sample.name => you can access field from class model
        isLoading = false;
      });
    } else {
      throw Exception('Failed to load photos');
    }
  }
  @override
  void initState() {
    // TODO: implement initState
    _fetchData();
    super.initState();
  }

  BoxDecoration myBoxDecoration() {
    return BoxDecoration(
      border: Border.all(color: Colors.blue),
      borderRadius: BorderRadius.circular(10),
      color: Colors.white,
    );
  }


  @override
  Widget build(BuildContext context) {
    FlutterMoneyFormatter fmf = FlutterMoneyFormatter(amount: 12345678.9012345);

    MoneyFormatterOutput fo = fmf.output;
    return Scaffold(
        body: isLoading
            ? Center(
          child: CircularProgressIndicator(),
        )
            : Container(
          height: height,
          child: ListView.builder(
              itemCount: list.length,
              scrollDirection: Axis.horizontal,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  margin: EdgeInsets.fromLTRB(0, 0, 10, 0),
                  width: 280.0,
                  height: height,
                  decoration: myBoxDecoration(),
                  child: Row(
                    children: <Widget>[
                      ClipRRect(
                          borderRadius: BorderRadius.only(bottomLeft: Radius.circular(10),topLeft: Radius.circular(10)),
                          child: Image(
                            width: 130,
                            height: height,
                            image: NetworkImage(
                                list[index].fotoPaket
                            ),
                            fit: BoxFit.fill,
                          )
                      ),

                      Flexible(
                        child: Container(
                          margin: EdgeInsets.only(left: 10),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            textDirection: TextDirection.ltr,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: <Widget>[
                              Container(
                                child: Text(
                                  list[index].namaPaket,
                                  style: new TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
                                ),
                              ),
                              Container(
                                margin: EdgeInsets.only(top: 5),
                                child: Text(
                                  list[index].kota,
                                  style: new TextStyle(fontSize: 16),
                                ),
                              ),
                              Container(
                                margin: EdgeInsets.only(top: 5),
                                child: Text(
                                  fmf.copyWith(
                                      amount: double.parse(list[index].hargaBawah),
                                      symbol: 'Rp',
                                      thousandSeparator: '.',
                                      fractionDigits: 0
                                  ).output.symbolOnLeft,
                                  style: new TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.red),
                                ),
                              ),
                            ],
                          ),
                        )
                      ),
                    ],
                  ),
                );
              }
          ),
        )
    );
  }
}